# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ec473e8de9b102e129ab250baabf061f19f621f59a6d036e2689441f29135fb11cd1c116b394f533da84ded57f64df741879a919349e2565942cba317c2c319

test:
  secret_key_base: 1920da2b7e80aa4327c9c4e7694ecc5294aacb605e8f9b67a34ad2aa5669f344112737ea1cd9bed2326f83e54020333c2e5f94bc6a4443eface6fc9b30b454b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
